---
- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: openjdk
      tags: openjdk
  roles:
    - role: ansible-role-jira
