---
- hosts: all
  remote_user: root
  become: true
  tasks:
     - name: check if ports are open
       ansible.builtin.wait_for:
        port: "{{ item }}"
        timeout: 2
       loop:
         - "8080"

     - name: see if the sample page returns 200
       ansible.builtin.uri:
         url: "http://127.0.0.1:8080/"
         return_content: yes
       register: result
       failed_when:
         - "'jira' not in result.content"
