---
- name: Verify
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Check if ports are open
      ansible.builtin.wait_for:
        port: "{{ item }}"
        timeout: 2
      loop:
        - "8080"
      changed_when: false
      failed_when: false

    - name: See if the sample page returns 200
      ansible.builtin.uri:
        url: "http://127.0.0.1:8080/"
        return_content: true
      changed_when: false
      register: result
      failed_when: false
       # - "'jira' not in result.content"
