---
- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: check page
      ansible.builtin.uri:
        url: "http://localhost:8080"
        status_code: "200"
        timeout: "300"
        return_content: true
      async: "300"
      poll: "10"
      register: result
      until: result.status == 200
      retries: 30

    - name: check result
      ansible.builtin.fail:
      when: "'jira' not in result.content"
